INSERT INTO authority(name) VALUES ('PATIENT');
INSERT INTO authority(name) VALUES ('PHARMACIST');
INSERT INTO authority(name) VALUES ('DERMATOLOGIST');
INSERT INTO authority(name) VALUES ('SUPPLIER');
INSERT INTO authority(name) VALUES ('PHARMACY_ADMIN');
INSERT INTO authority(name) VALUES ('PHARMACY_SYSTEM_ADMIN');